# Generated by Django 4.2.6 on 2023-10-28 18:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('a', 'student'), ('b', 'staff'), ('c', 'admin'), ('d', 'editor')], max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('nationality', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
