# Generated by Django 5.0 on 2023-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(choices=[('a', 'marketing'), ('b', 'HR'), ('c', 'digital marketing'), ('d', 'developers')], max_length=100)),
                ('Salary', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Address', models.TextField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('Approve', models.BooleanField()),
            ],
        ),
    ]
