# Generated by Django 5.0 on 2023-12-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.TextField()),
                ('Emp_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.employee')),
            ],
        ),
    ]
