# Generated by Django 5.0 on 2023-12-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_suggestionmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Date', models.DateField()),
                ('Reason', models.CharField(max_length=100)),
                ('EmployeeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.employee')),
            ],
        ),
    ]
