# Generated by Django 5.0 on 2024-04-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_employeename_leavereport_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emply_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(choices=[('a', 'marketing'), ('b', 'HR'), ('c', 'digital marketing'), ('d', 'developers')], max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountData', models.TextField()),
                ('Emply_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.employee')),
            ],
        ),
    ]
