# Generated by Django 5.0 on 2023-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Emp_Team', models.CharField(choices=[('a', 'marketing'), ('b', 'graphic designer'), ('c', 'Developer'), ('d', 'degital marketing'), ('e', 'admin')], max_length=100)),
                ('Salary', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Approve_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
